spring.application.name=ChatterBox
debug=true
logging.level.org.springframework.boot.autoconfigure=warn

# DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ChatterBoxDB      
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
