package com.Chatting.Application.service;

import com.Chatting.Application.dto.MessagesDto;
import com.Chatting.Application.entities.Messages;
import com.Chatting.Application.entities.Room;
import com.Chatting.Application.repository.MessagesRepository;
import com.Chatting.Application.repository.RoomRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.modelmapper.ModelMapper;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Service
@RequiredArgsConstructor
@Slf4j
public class MessagesServiceImpl implements MessagesService {
    private final MessagesRepository messagesRepository;
    private final RoomRepository roomRepository;
    private final ModelMapper modelMapper;

    @Override
    public MessagesDto saveMessage(MessagesDto messagesDto) {
        log.info("Saving message from roomId: {}, sender: {}", messagesDto.getRoomId(), messagesDto.getSender());

        // Find the room by roomId
        Room room = roomRepository.findByRoomId(messagesDto.getRoomId())
                .orElseThrow(() -> new RuntimeException("Room with Id: " + messagesDto.getRoomId() + " not found!"));

        // Create Messages entity manually (avoid ModelMapper issue with id field)
        Messages message = new Messages();
        message.setSender(messagesDto.getSender());
        message.setContent(messagesDto.getContent());
        message.setTimeStamp(messagesDto.getTimeStamp() != null ? messagesDto.getTimeStamp() : LocalDateTime.now());
        message.setRoom(room);
        // Note: id will be auto-generated by database, so we don't set it

        // Save the message
        Messages savedMessage = messagesRepository.save(message);

        // Convert Entity back to DTO
        MessagesDto savedMessageDto = modelMapper.map(savedMessage, MessagesDto.class);
        savedMessageDto.setRoomId(messagesDto.getRoomId()); // Set roomId in DTO

        log.info("Message saved successfully with id: {}", savedMessage.getId());
        return savedMessageDto;
    }
}
